spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        package-to-scan: com.javanautas.fakeapius.infrastructure.entities
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    loadbalancer:
      ribbon:
        enable: true

topico:
  fake-api:
    consumer:
      nome: fake-api-consumer-products-v2
      group-id: javanauta
    producer:
      nome: fake-api-producer-products-v2

fake-api:
  url: https://fakestoreapi.com

server:
  port: 8181
